[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cacheDirectories = [
  "node_modules",
  "server/node_modules"
]

[phases.build]
cmds = ["npm run build"]
cacheDirectories = [
  "node_modules",
  "server/node_modules"
]

[start]
cmd = "npm start"

