[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "cd server && npm install"
]
cacheDirectories = [
  "node_modules",
  "server/node_modules"
]

[phases.build]
cmds = ["npx vite build"]
cacheDirectories = [
  "node_modules",
  "server/node_modules"
]

[start]
cmd = "npm start"

